<font size="5">Introdução ao Python</font>

<font size="4">Numpy</font>

In [7]:
import numpy as np

In [9]:
#Cria uma matriz unidimensional

mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [11]:
#Cria o array com um tipo especifico (float 64bits)

mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [13]:
#Cria o array com um tipo especifico (int 32bits)

mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1 2 3]
<class 'numpy.ndarray'>


In [15]:
#Muda o tipo do array

mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.94293])
print(mtnew)

#Quando transformamos o float para int os valores são truncados

mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      3.6     -5.1      9.42     4.94293]
[ 1  3 -5  9  4]


In [17]:
#Também pode ser feito o inverso

mt5 = np.array([1,2,3,4])
print(mt5)
mt5float = mt5.astype(np.float64)
print(mt5float)

[1 2 3 4]
[1. 2. 3. 4.]


In [19]:
#Cria uma matriz bidimensional

mtbi = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mtbi)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [21]:
#Criar arrays vazios tipificados

#Empty significa que não são inicializados, não que são vazios.

vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-------")

#Cria uma matriz 4x3 com valores zero

zeros = np.zeros([4,3])
print(zeros)
print("-------")

#Com valores igual a um

um = np.ones([5,7])
print(um)
print("-------")

#Cria uma matriz quadrada com diagonal principal com valores 1 e os outros valores 0 

diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
#Valores aleatórios entre zero e um

ale = np.random.random((5))
print(ale)
print("------------")

#Valores aleatórios distribuicao normal contendo negativos

ale2 = np.random.randn((5))
print(ale2)
print("------------")

#Valores aleatórios 3x4

ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.89127367 0.67588256 0.47164592 0.7998769  0.31698506]
------------
[-0.46880711  0.73928625 -0.22964374  0.20985348  1.59599415]
------------
[[4.15274713 2.47970036 5.55500449 0.60886425]
 [7.37164796 5.96149811 4.7470443  7.59860781]
 [9.93407303 0.08496724 7.33304523 3.98069123]]


In [25]:
#Outra forma de gerar aleatórios
#Uso de semente
#1 é a semente, sempre que utilizar o 1 irá gerar os mesmos numeros

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

#Gerar inteiros // será um numero até 10 em uma matriz 3x4

ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [27]:
#Método unique remove repetições

j = np.array([1,2,3,3,4,4,5,6,7,8,9,9,10])
j = np.unique(j)
print(j)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
#Funções especificas
#Cria a matrizx bidimencional k

k = np.array([[17,22,43],[27,25,14],[15,24,32]])

#Mostra a matriz k

print(k)

#Mostra um elemento especifico da matriz k
#0 se refere a linha e o 1 a coluna

print(k[0][1])

#Mostra o tamanho das dimensoes da matriz k

print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [31]:
#Funções Matemáticas

#mostra o maior valor da matriz k
print(k.max())
#mostra o menor valor da matriz k
print(k.min())
#mostra a soma dos valores da matriz k
print(k.sum())
#mostra a media dos valores da matriz k
print(k.mean())
#mostra o valor do desvio padrao (standard deviation) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [33]:
#Funções universais, aplicadas a todos os elementos

#Mostra o valor da raiz qudrada de todos os elementos

k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))

#Mostra o valor do exponencial de todos os elementos

print (np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [35]:
#Extração de elementos

m = np.array([1,2,3,4,5,6])

#Mostra o elemento da posicao 2

print(m[1])
print("-----------------")

#Mostra o array criado a partr da posicao 0, sempre ignora o último elemento

print(m[0:2])
print("-----------------")

#Mostra o array criado a partir da segunda posicao
#Até todo o restante do array

print(m[1:])
print("-----------------")

#Mostra o array craiado a partir da antepenuntima posicao ate o final
print(m[-3:])

2
-----------------
[1 2]
-----------------
[2 3 4 5 6]
-----------------
[4 5 6]


In [37]:
#Extração de linhas e colunas

l = np.array([[4,5],[6,1],[7,4]])
print(l)
print("-----------------")

#Primeira linha, todas as colunas

l_linha1 = l[0, :]
print(l_linha1)
print("-----------------")

#Segunda linha

l_linha2 = l[1, :]
print(l_linha2)
print("-----------------")

#Todas as linhas, primeira coluna

l_coluna1 = l[:,0]
print(l_coluna1)


[[4 5]
 [6 1]
 [7 4]]
-----------------
[4 5]
-----------------
[6 1]
-----------------
[4 6 7]


In [39]:
#Adição e multiplicação de matrizes

n = np.array([[1, 2],[3, 4]])
o = np.array([[1, 1],[1, 1]])
somamt = n + o
print(somamt)
print("-----------------")
multmt = n * o
print(multmt)
print("-----------------")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q) #a matriz unimensional é somada a todas as matrizes da matriz multdimensional

[[2 3]
 [4 5]]
-----------------
[[1 2]
 [3 4]]
-----------------
[[3 3]
 [5 5]
 [7 7]]


In [41]:
#Transposição rearranja um conjunto de 15 elementos de 0 a 14
#em 3 linhas e 5 colunas

f = np.arange(15).reshape((3, 5))

#Mostra a matrizes transposta entre linha e coluna

print(f)
print("-----------------")

s= f.T #é como se transformasse as linhas em colunas e colunas em linhas
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [43]:
#Outra forma de fazer, mesmo resultado

r = np.arange(15).reshape((3, 5))
print(r)
print("-----------------")

#Rearranja um conjunto de 15 elementos
#Mostra a matriz transposta entre linha e coluna

s = r.transpose((1,0))
print(s)              

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [45]:
#Expressões Lógicas usando where

#Criando matriz com valores aleatórios positivos e negativos

v = np.random.randn(4, 4)
print(v)

#Criando matriz com valores booleanos baseado no array v
x = v > 0
print(x)

#Criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where (x > 0, 1, -1)
print(z)

[[-1.52121768  0.57463536 -0.48513713 -1.40811694]
 [ 1.00274914 -0.57890815  0.76866788  0.27418328]
 [ 1.33360513  1.27254503  2.03965222  1.24211247]
 [ 0.46204303  0.12352983  0.27942848  2.3838147 ]]
[[False  True False False]
 [ True False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[-1  1 -1 -1]
 [ 1 -1  1  1]
 [ 1  1  1  1]
 [ 1  1  1  1]]
